### ISSUE TITLE
执行异常：Cannot read property 'subtle' of undefined

### ISSUE THREAD

**Issue by nineya** [EtherDream/freecdn#10]
执行 `freecdn js -save` 命令抛出了异常，貌似是和 `crypto` 不兼容？
我的 nodejs 版本是 v14.14.0
异常内容如下：
```
F:\IntelliJProject\halo-theme-dream>freecdn js -save
F:\IntelliJProject\halo-theme-dream\node_modules\freecdn\lib\cmd-key.js:8
const subtle = crypto_1.webcrypto.subtle;
                                  ^

TypeError: Cannot read property 'subtle' of undefined
    at Object.<anonymous> (F:\IntelliJProject\halo-theme-dream\node_modules\freecdn\lib\cmd-key.js:8:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (F:\IntelliJProject\halo-theme-dream\node_modules\freecdn\lib\cmd-manifest.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

```

**Comment by EtherDream** [comment]
nodejs 版本太低了，不支持这个 api，使用 15+ 就可以了。
